language: android
jdk: oraclejdk8

# Install Android SDK
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository

# Cache gradle dependencies
# https://docs.travis-ci.com/user/languages/android/#Caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  - GRADLE_OPTS=-Xmx2048m

script:
  # Lint fails because travis doesn't have platform-tools 24
  # https://github.com/travis-ci/travis-ci/issues/6699
  #- ./gradlew lint
  - ./gradlew core:test
  - ./gradlew server:release
  - ./gradlew integration:assemble
  - ./gradlew android:assembleRelRelease || ./gradlew android:assembleRelRelease
